### ISSUE TITLE
What is the different between your model and other mobilenet model?

### ISSUE THREAD

**Issue by nvnnghia** [GustavZ/realtime_object_detection#13]
Hi, I run your project using mobinet v1.  But the speed is only a half compare to your model. When I tried mobinet v2, I got error. Therefore I want to ask What is the different between your model and other mobilenet model?

Second problem is:
when I used your .config file to train on Pascal VOC data, after training I got model file and do object detection using your code. But, got this error:
`ValueError: graph_def is invalid at node u'Preprocessor/map/TensorArray_2': Input tensor 'Preprocessor/map/strided_slice:0' not found in graph_def`. Any suggestion?? Thank you!

**Comment by nvnnghia** [comment]
@GustavZ any suggestion?

**Comment by GustavZ** [comment]
hello @nvnnghia this project works with and only for ssd_mobilenet which is supplied by tensorflows object_detection model zoo.

The reason why is the following:
If you take a look at my code you see that it manually splits the model into two parts, one for gpu and one for cpu. This only works because it was manually investigated and HARD CODED where the exact layer names are that are good to use as a split point.

NOW: IF you use another model, that maybe has other layer names, even though it is a SSD MOBILENET, it won't work!

My hack/work is not scalable, but still you can reproduce it if you log the time of each layer and finf a point to split your model, but you need to code that by your own.

Unfortuantely there is no other way to do so.

If you want to know how to log your model with the time used in each layer, have a look at my other prokect` realtime_segmentation` and in this the file `test.py`, this file creates such a log file.

I hope i could make some things clear to you.

**Comment by Eoinoe** [comment]
@nvnnghia  Hey, I'm looking to work on a similar project. I was wondering if you'd be interested in getting in contact with me so we could maybe discuss ways to get it working for mobilenet_v2.

**Comment by nvnnghia** [comment]
yes, I'm interest to learn.

**Comment by azadef** [comment]
Hi, Do you think the splitting would work on faster-rcnn models? I tried finding a layer for splitting, but the layers after the splitting point are dependent on the ones before.

**Comment by GustavZ** [comment]
@azadef it could be possible, but it won’t be as straight forward / easy as with ssd.
But if you achieve it, it would be great to hear of you :)

**Comment by azadef** [comment]
@GustavZ Sure, will let you know if I succeed :)
